apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "mm-example-srv"
spec:
  targets:
  - name: mm-example-srv-1
  - name: mm-example-srv-2
  peers:
  - mtls: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mm-example-api
spec:
  host: mm-example-api
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mm-example-srv-1
spec:
  host: mm-example-srv-1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mm-example-srv-2
spec:
  host: mm-example-srv-2
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---