server:
  port: 9090

spring:
  application:
    name: mm-example-client
  sleuth:
    sampler:
      probability: 1

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true

grpc:
  enableReflection: true
  client:
    mm-example:
      # address: 'static://localhost:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

