// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Services int32

const (
	Services_mm_example_api   Services = 0
	Services_mm_example_srv_1 Services = 1
	Services_mm_example_srv_2 Services = 2
)

var Services_name = map[int32]string{
	0: "mm_example_api",
	1: "mm_example_srv_1",
	2: "mm_example_srv_2",
}
var Services_value = map[string]int32{
	"mm_example_api":   0,
	"mm_example_srv_1": 1,
	"mm_example_srv_2": 2,
}

func (x Services) String() string {
	return proto.EnumName(Services_name, int32(x))
}
func (Services) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_1bf7f1c9e48d69fd, []int{0}
}

type ReqMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMessage) Reset()         { *m = ReqMessage{} }
func (m *ReqMessage) String() string { return proto.CompactTextString(m) }
func (*ReqMessage) ProtoMessage()    {}
func (*ReqMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_1bf7f1c9e48d69fd, []int{0}
}
func (m *ReqMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMessage.Unmarshal(m, b)
}
func (m *ReqMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMessage.Marshal(b, m, deterministic)
}
func (dst *ReqMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMessage.Merge(dst, src)
}
func (m *ReqMessage) XXX_Size() int {
	return xxx_messageInfo_ReqMessage.Size(m)
}
func (m *ReqMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMessage proto.InternalMessageInfo

func (m *ReqMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RspMessage struct {
	Response             *RspMessage_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Chain                []string             `protobuf:"bytes,3,rep,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RspMessage) Reset()         { *m = RspMessage{} }
func (m *RspMessage) String() string { return proto.CompactTextString(m) }
func (*RspMessage) ProtoMessage()    {}
func (*RspMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_1bf7f1c9e48d69fd, []int{1}
}
func (m *RspMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspMessage.Unmarshal(m, b)
}
func (m *RspMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspMessage.Marshal(b, m, deterministic)
}
func (dst *RspMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspMessage.Merge(dst, src)
}
func (m *RspMessage) XXX_Size() int {
	return xxx_messageInfo_RspMessage.Size(m)
}
func (m *RspMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RspMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RspMessage proto.InternalMessageInfo

func (m *RspMessage) GetResponse() *RspMessage_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *RspMessage) GetChain() []string {
	if m != nil {
		return m.Chain
	}
	return nil
}

type RspMessage_Response struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspMessage_Response) Reset()         { *m = RspMessage_Response{} }
func (m *RspMessage_Response) String() string { return proto.CompactTextString(m) }
func (*RspMessage_Response) ProtoMessage()    {}
func (*RspMessage_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_1bf7f1c9e48d69fd, []int{1, 0}
}
func (m *RspMessage_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspMessage_Response.Unmarshal(m, b)
}
func (m *RspMessage_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspMessage_Response.Marshal(b, m, deterministic)
}
func (dst *RspMessage_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspMessage_Response.Merge(dst, src)
}
func (m *RspMessage_Response) XXX_Size() int {
	return xxx_messageInfo_RspMessage_Response.Size(m)
}
func (m *RspMessage_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_RspMessage_Response.DiscardUnknown(m)
}

var xxx_messageInfo_RspMessage_Response proto.InternalMessageInfo

func (m *RspMessage_Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqMessage)(nil), "com.hbchen.ReqMessage")
	proto.RegisterType((*RspMessage)(nil), "com.hbchen.RspMessage")
	proto.RegisterType((*RspMessage_Response)(nil), "com.hbchen.RspMessage.Response")
	proto.RegisterEnum("com.hbchen.Services", Services_name, Services_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleServiceClient interface {
	Call(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*RspMessage, error)
}

type exampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleServiceClient(cc *grpc.ClientConn) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) Call(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*RspMessage, error) {
	out := new(RspMessage)
	err := c.cc.Invoke(ctx, "/com.hbchen.ExampleService/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
type ExampleServiceServer interface {
	Call(context.Context, *ReqMessage) (*RspMessage, error)
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.hbchen.ExampleService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).Call(ctx, req.(*ReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.hbchen.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _ExampleService_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_service_1bf7f1c9e48d69fd) }

var fileDescriptor_service_1bf7f1c9e48d69fd = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0xb8, 0x92, 0xf3,
	0x73, 0xf5, 0x32, 0x92, 0x92, 0x33, 0x52, 0xf3, 0x94, 0x14, 0xb8, 0xb8, 0x82, 0x52, 0x0b, 0x7d,
	0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0xa5, 0x7a, 0x2e, 0xae, 0xa0, 0xe2, 0x02, 0x98, 0x0a,
	0x6b, 0x2e, 0x8e, 0xa2, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0x6e, 0x23, 0x79, 0x3d, 0x84, 0x71, 0x7a, 0x08, 0x95, 0x7a, 0x41, 0x50, 0x65, 0x41, 0x70, 0x0d,
	0x42, 0x22, 0x5c, 0xac, 0xc9, 0x19, 0x89, 0x99, 0x79, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0x9c, 0x41,
	0x10, 0x8e, 0x94, 0x1c, 0x17, 0x07, 0x4c, 0x2d, 0x36, 0x07, 0x68, 0x79, 0x71, 0x71, 0x04, 0x43,
	0xdc, 0x5f, 0x2c, 0x24, 0xc4, 0xc5, 0x97, 0x9b, 0x1b, 0x9f, 0x5a, 0x91, 0x98, 0x5b, 0x90, 0x93,
	0x1a, 0x9f, 0x58, 0x90, 0x29, 0xc0, 0x20, 0x24, 0xc2, 0x25, 0x80, 0x24, 0x56, 0x5c, 0x54, 0x16,
	0x6f, 0x28, 0xc0, 0x88, 0x45, 0xd4, 0x48, 0x80, 0xc9, 0xc8, 0x8b, 0x8b, 0xcf, 0x15, 0x22, 0x04,
	0x35, 0x52, 0xc8, 0x82, 0x8b, 0xc5, 0x39, 0x31, 0x27, 0x47, 0x48, 0x0c, 0xc5, 0x1b, 0xf0, 0x20,
	0x91, 0x12, 0xc3, 0xee, 0x3d, 0x25, 0x06, 0x27, 0xf6, 0x28, 0x56, 0x70, 0x78, 0x26, 0xb1, 0x81,
	0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x40, 0x71, 0x66, 0x6d, 0x01, 0x00, 0x00,
}
