# handler for adapter auth adapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: auth-handler
  namespace: istio-system
spec:
  adapter: auth-adapter
  connection:
    #address: "[::]:44225"
    address: "auth-adapter-service:44225"
    #address: "35.184.34.117:44225"
  params:
    token: "abc"
    redis_server_url: ""
    connection_pool_size: 1
---
# instance for adapter auth adapter
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: auth-instance
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      properties:
        token:  request.headers["x-custom-token"]
        req_host: request.host
        #req_path: request.path
        #req_method: request.method
        #req_referer: request.referer
        #req_agent: request.useragent
---
# rule to dispatch to handler auth-handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: auth-rule
  namespace: istio-system
spec:
  match: request.host == "mm-example-api"
  actions:
  - handler: auth-handler.istio-system
    instances:
    - auth-instance.istio-system
---