apiVersion: v1
kind: Service
metadata:
  name: mm-example-auth-adapter-service
  namespace: istio-system
  labels:
    app: auth-adapter
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 44225
    targetPort: 44225
  selector:
    app: auth-adapter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mm-example-auth-adapter
  namespace: istio-system
  labels:
    app: auth-adapter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-adapter
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: auth-adapter
        image: hbchen/micro-mesh-example-auth-adapter:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 44225